### ISSUE TITLE
Webpack (develop) => master branch merge after diff check and manual tests

### ISSUE THREAD

**Issue by sanak** [gtt-project/redmine_gtt#71]
@dkastl @smellman  
The initial version was released, so I will check this by 4/30 before merging develop => master.

---

- [x] Merge `master` branch update to `develop` branch, once
   - [x] #60: Do not hide map by default
   - [x] #67: Supported Gemfile rgeo-activerecord/activerecord-postgis-adapter compatible versions with environment variables
   - [x] #68: Show error message when updating project geometry with invalid multi polygon
- [x] Check code diff between `master` <=> `develop`
- [x] Manual tests (diff between `master` <=> `develop`)

**Comment by sanak** [comment]
Manual test diffs:
- [ ] Map icon looks is different:
   - main:  
      ![main_map_icon](https://user-images.githubusercontent.com/629923/117619280-074d5f80-b1aa-11eb-9aa2-a0071cdaeb2e.png)
   - develop:  
      ![dev_map_icon](https://user-images.githubusercontent.com/629923/117619308-103e3100-b1aa-11eb-978f-fae0e268587e.png)
- [ ] Map popup is different:
   - main: (When closing popup, then recover map icon)  
      ![main_popup](https://user-images.githubusercontent.com/629923/117619705-8e023c80-b1aa-11eb-9376-4a38517dcabb.png)
   - develop: (When closing popup, then map icon is not recovered)  
      ![dev_popup](https://user-images.githubusercontent.com/629923/117619743-98bcd180-b1aa-11eb-9439-6b61b0a33be1.png)
- [ ] Issues list view's map collapse status is different (probably my merge miss):  
   - main:  
      ![main_location_collapse](https://user-images.githubusercontent.com/629923/117622082-387b5f00-b1ad-11eb-9e09-8175e62bbbaf.png)
   - develop:  
      ![dev_location_collapse](https://user-images.githubusercontent.com/629923/117622113-40d39a00-b1ad-11eb-9f76-0e7887e5ae89.png)
- [ ] Slight space (margin or padding) difference in layer panel:
   - main:  
      ![main_layer_panel](https://user-images.githubusercontent.com/629923/117623009-39f95700-b1ae-11eb-844d-e3739def57ff.png)
   - develop:  
      ![dev_layer_panel](https://user-images.githubusercontent.com/629923/117623043-454c8280-b1ae-11eb-8849-c8f5133d66ed.png)
- [ ] Plugin settings tracker icon order difference:  
   ![tracker_icons_order](https://user-images.githubusercontent.com/629923/117626249-dcffa000-b1b1-11eb-8b29-498abb5fca6a.png)
   - main: mcr icons first
   - develop: mcr icons last (But I prefer this order)

**Comment by dkastl** [comment]
Thanks for checking!
I think changes can be also due to newer versions of OL and OL-ext. And sometimes changes don't really matter, because the settings made before were just the defaults.

**Comment by sanak** [comment]
Okay, thanks for confirmation.
I will try to fix those to be familiar with new system, once.

**Comment by sanak** [comment]
@dkastl (CC: @smellman)
- About Map Icon difference, I completely forgot the following ol-ext enhancement (), but I think that it's better to keep simple as much as possible, so I am thinking to use ol-ext original `blazon` style (https://viglino.github.io/ol-ext/examples/style/map.style.font.html).
- About mcr icons order in plugin settings, I noticed that some icons are duplicated (douro, street and road), but is it better to remove mcr icons, once ?
   - I felt that plugin settings icon size is too small, so I am thinking to add `font-size: 1.5em; vertical-align: middle` to the icon part.

I am working on #72 PR branch now.

**Comment by dkastl** [comment]
I think it's a good idea to reduce the icons to some defaults (without MCR icons). We just need to describe how to add custom icons ... and have some way to do this easily. Not sure what is a good way though.

Increasing icon size is also fine.

**Comment by sanak** [comment]
@dkastl Okay, thanks for confirmation!

**Comment by sanak** [comment]
@dkastl  
Well, I noticed that FontAwesome is not loaded correctly on both `main` and `develop` branch, but is it bad to add any extra fonts (fontmaki2, FontAwesome .etc) ?  
https://viglino.github.io/ol-ext/examples/style/map.style.font.html

If so, keeping mcr-icons may be better, because fontmaki default set is quite few, so adjusting mcr-icons itself by removing duplicated icons may be good.

**Comment by sanak** [comment]
By the way, I felt that current font including way is enough simple and customizable in `src/index.ts`, but `ol-ext` npm package doesn't include `fontmaki.css` and `fontmaki2.css`, so I may copy those to `src/stylesheets/`, then remove `fontmaki` definition from current `src/stylesheets/fonts.scss`. (Then controlling arbitrary fonts (like only fontmaki2 .etc) becomes possible.)

**src/index.ts**
```ts
import 'ol/ol.css'
import 'ol-ext/dist/ol-ext.min.css'
import './stylesheets/fonts.scss'
import './stylesheets/app.scss'
import './components/fontmaki-def'
import './components/mcricon-def'
:
```

**Comment by sanak** [comment]
Well, about font, I only change font order (mcr-icons first).

**Comment by dkastl** [comment]
I don't remember why which fonts were added, but `ol-ext` does this for providing more map icons. And some icons are needed for toolbars. But in general I agree, that fewer icons are better ... on the long term it's nice if the icon set can be custom built if needed.
